using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


//You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

//Return the minimum number of steps to make the given string empty.

//A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.

//A string is called palindrome if is one that reads the same backward as well as forward.

namespace LeetCode
{
    public class RemovePalindromicSubsequences
    {
        public int RemovePalindromeSub(String s)
        {
            if (IsPalindrome(s)) return 1;
            return 2;
        }

        private bool IsPalindrome(String s)
        {
            int i = 0, n = s.Length;
            while (i <= n / 2)
                if (s[i] != s[n - 1 - i++]) return false;
            return true;
        }

        //Solution with StringBuilder:
        public int RemovePalindromeSub2(String s)
        {
            if (s.Equals(new String(s).Reverse())) return 1;
            return 2;
        }


    }
}
